# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  cloudfoundry: circleci/cloudfoundry@0.1.52

jobs:
  test:
    docker:
      - image: circleci/ruby

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  build_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - cloudfoundry/push:
          appname: andrew-sinatra
          endpoint: 'https://api.fr.cloud.gov'
          manifest: 'manifest.yml'
          org: sandbox-gsa
          package: '.'
          space: andrew.hyder
          requires:
            - test
          filters:
            branches:
              only: master
      